//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA_DETAILS
    {
        public string MaDanhGia { get; set; }
        public int HangMuc { get; set; }
        public Nullable<int> MucDo { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DANH_GIA DANH_GIA { get; set; }
        public virtual HANG_MUC HANG_MUC { get; set; }
    }
}
