//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG_MUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG_MUC()
        {
            this.DANHGIA_DETAILS = new HashSet<DANHGIA_DETAILS>();
        }
    
        public int ID { get; set; }
        public string TenHangMuc { get; set; }
        public Nullable<bool> Hide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA_DETAILS> DANHGIA_DETAILS { get; set; }
    }
}
