//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_NHAN_VIEN
    {
        public int MaHD { get; set; }
        public string MSNV { get; set; }
        public string VaiTro { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HOAT_DONG HOAT_DONG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
