//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_TAITRO
    {
        public int ID_TaiTro { get; set; }
        public int MaHD { get; set; }
        public string NoiDung { get; set; }
    
        public virtual HOAT_DONG HOAT_DONG { get; set; }
        public virtual TAI_TRO TAI_TRO { get; set; }
    }
}
