//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAN_VIEN()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
            this.HD_NHAN_VIEN = new HashSet<HD_NHAN_VIEN>();
        }
    
        public string MSNV { get; set; }
        public string HoTen { get; set; }
        public string CoSo { get; set; }
        public Nullable<bool> Hide { get; set; }
    
        public virtual CO_SO CO_SO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_NHAN_VIEN> HD_NHAN_VIEN { get; set; }
    }
}
