//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHU_TRACH
    {
        public string MaQL { get; set; }
        public string SuKien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual QUAN_LY QUAN_LY { get; set; }
    }
}
