//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlyeventskhachsanEntities : DbContext
    {
        public quanlyeventskhachsanEntities()
            : base("name=quanlyeventskhachsanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CO_SO> CO_SO { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIA { get; set; }
        public virtual DbSet<DANHGIA_DETAILS> DANHGIA_DETAILS { get; set; }
        public virtual DbSet<DOI_TAC> DOI_TAC { get; set; }
        public virtual DbSet<HANG_MUC> HANG_MUC { get; set; }
        public virtual DbSet<HD_DOITAC> HD_DOITAC { get; set; }
        public virtual DbSet<HD_NHAN_VIEN> HD_NHAN_VIEN { get; set; }
        public virtual DbSet<HD_QUANLY> HD_QUANLY { get; set; }
        public virtual DbSet<HD_TAITRO> HD_TAITRO { get; set; }
        public virtual DbSet<HOAT_DONG> HOAT_DONG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<PHU_TRACH> PHU_TRACH { get; set; }
        public virtual DbSet<QUAN_LY> QUAN_LY { get; set; }
        public virtual DbSet<TAI_CHINH> TAI_CHINH { get; set; }
        public virtual DbSet<TAI_TRO> TAI_TRO { get; set; }
    }
}
