//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_LY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUAN_LY()
        {
            this.HD_QUANLY = new HashSet<HD_QUANLY>();
            this.PHU_TRACH = new HashSet<PHU_TRACH>();
        }
    
        public string MaQL { get; set; }
        public string HoTenLot { get; set; }
        public string Ten { get; set; }
        public string CoSo { get; set; }
        public Nullable<bool> Hide { get; set; }
    
        public virtual CO_SO CO_SO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_QUANLY> HD_QUANLY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHU_TRACH> PHU_TRACH { get; set; }
    }
}
