//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyeventskhachsan.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_CHINH
    {
        public int ID_TaiChinh { get; set; }
        public int MaHD { get; set; }
        public Nullable<decimal> UEF { get; set; }
        public Nullable<decimal> TaiTro { get; set; }
        public string Khac { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Hide { get; set; }
    
        public virtual HOAT_DONG HOAT_DONG { get; set; }
    }
}
